-- Seed 15 dummy blog posts
-- Run this manually in Supabase SQL Editor to populate blog posts

INSERT INTO posts (title, slug, content, excerpt, featured_image, status, author_id, published_at) VALUES 
('Inovasi Teknologi Konstruksi di Era Digital', 'inovasi-teknologi-konstruksi-era-digital', '<p>Teknologi konstruksi terus berkembang pesat di era digital. Dari penggunaan Building Information Modeling (BIM) hingga drone untuk survei lokasi, industri konstruksi mengalami transformasi besar.</p><p>PT Aratindo Karya Utama berkomitmen untuk mengadopsi teknologi terkini dalam setiap proyek yang kami kerjakan. Hal ini tidak hanya meningkatkan efisiensi, tetapi juga kualitas hasil akhir yang lebih baik.</p><p>Dengan teknologi, kami dapat meminimalkan kesalahan, menghemat waktu, dan memberikan nilai lebih kepada klien kami.</p>', 'Bagaimana teknologi digital mengubah landscape industri konstruksi modern', 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800', 'published', (SELECT id FROM profiles LIMIT 1), NOW() - INTERVAL '1 day'),

('Membangun Infrastruktur Berkelanjutan untuk Masa Depan', 'membangun-infrastruktur-berkelanjutan', '<p>Infrastruktur berkelanjutan bukan lagi pilihan, tetapi kebutuhan. Kami fokus pada pembangunan yang ramah lingkungan dan efisien energi.</p><p>Setiap proyek dirancang dengan mempertimbangkan dampak jangka panjang terhadap lingkungan. Dari pemilihan material hingga sistem energi, semua aspek dioptimalkan untuk keberlanjutan.</p><p>Investasi dalam infrastruktur berkelanjutan adalah investasi untuk generasi mendatang.</p>', 'Pendekatan PT Aratindo dalam menciptakan infrastruktur ramah lingkungan', 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800', 'published', (SELECT id FROM profiles LIMIT 1), NOW() - INTERVAL '2 days'),

('Standar Keselamatan Kerja di Proyek Konstruksi', 'standar-keselamatan-kerja-konstruksi', '<p>Keselamatan kerja adalah prioritas utama di setiap proyek PT Aratindo Karya Utama. Kami menerapkan standar keselamatan internasional yang ketat.</p><p>Dari pelatihan rutin hingga penyediaan alat pelindung diri yang memadai, setiap aspek keselamatan diperhatikan dengan seksama.</p><p>Tim kami yang berpengalaman memastikan setiap pekerja kembali dengan selamat ke keluarga mereka setiap hari.</p>', 'Komitmen kami terhadap keselamatan pekerja dan lingkungan kerja yang aman', 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800', 'published', (SELECT id FROM profiles LIMIT 1), NOW() - INTERVAL '3 days'),

('Manajemen Proyek yang Efektif dalam Konstruksi', 'manajemen-proyek-efektif-konstruksi', '<p>Manajemen proyek yang baik adalah kunci kesuksesan setiap pembangunan. Kami menggunakan metodologi terbukti untuk memastikan proyek selesai tepat waktu dan sesuai anggaran.</p><p>Komunikasi yang transparan dengan klien dan koordinasi yang solid antar tim membuat setiap proyek berjalan lancar.</p><p>Pengalaman lebih dari satu dekade membuat kami ahli dalam mengatasi berbagai tantangan proyek.</p>', 'Strategi dan metodologi manajemen proyek yang kami terapkan', 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800', 'published', (SELECT id FROM profiles LIMIT 1), NOW() - INTERVAL '4 days'),

('Peran BIM dalam Efisiensi Konstruksi', 'peran-bim-efisiensi-konstruksi', '<p>Building Information Modeling (BIM) telah merevolusi cara kami merencanakan dan melaksanakan proyek konstruksi. Teknologi ini memungkinkan visualisasi 3D yang detail sebelum konstruksi dimulai.</p><p>Dengan BIM, kami dapat mengidentifikasi dan menyelesaikan masalah potensial di tahap perencanaan, menghemat waktu dan biaya yang signifikan.</p><p>Klien kami mendapatkan preview yang realistis dari hasil akhir proyek mereka.</p>', 'Bagaimana BIM meningkatkan akurasi dan efisiensi dalam konstruksi', 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800', 'published', (SELECT id FROM profiles LIMIT 1), NOW() - INTERVAL '5 days'),

('Material Konstruksi Inovatif dan Ramah Lingkungan', 'material-konstruksi-inovatif-ramah-lingkungan', '<p>Pemilihan material yang tepat sangat penting untuk hasil konstruksi yang berkualitas dan berkelanjutan. Kami terus mengeksplorasi material inovatif yang ramah lingkungan.</p><p>Dari beton hijau hingga material daur ulang, kami berkomitmen pada praktik konstruksi yang bertanggung jawab.</p><p>Material berkualitas tinggi tidak hanya tahan lama tetapi juga mengurangi jejak karbon proyek.</p>', 'Eksplorasi material konstruksi modern yang ramah lingkungan', 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800', 'published', (SELECT id FROM profiles LIMIT 1), NOW() - INTERVAL '6 days'),

('Transformasi Digital di Industri Konstruksi Indonesia', 'transformasi-digital-industri-konstruksi', '<p>Industri konstruksi Indonesia sedang mengalami transformasi digital yang pesat. Teknologi cloud, IoT, dan AI mulai diintegrasikan dalam proses konstruksi.</p><p>PT Aratindo Karya Utama berada di garis depan adopsi teknologi ini, memastikan kami tetap kompetitif dan memberikan nilai terbaik kepada klien.</p><p>Digitalisasi membuka peluang baru untuk efisiensi dan inovasi.</p>', 'Bagaimana digitalisasi mengubah cara kerja industri konstruksi', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800', 'published', (SELECT id FROM profiles LIMIT 1), NOW() - INTERVAL '7 days'),

('Konstruksi Gedung Tinggi: Tantangan dan Solusi', 'konstruksi-gedung-tinggi-tantangan-solusi', '<p>Membangun gedung tinggi memiliki tantangan unik yang memerlukan keahlian khusus. Dari fondasi yang kuat hingga sistem struktural yang kompleks, setiap detail harus sempurna.</p><p>Tim kami memiliki pengalaman ekstensif dalam proyek-proyek gedung tinggi, mengatasi tantangan dengan solusi inovatif.</p><p>Keselamatan, efisiensi, dan kualitas adalah prioritas utama dalam setiap proyek gedung tinggi kami.</p>', 'Pengalaman dan keahlian kami dalam konstruksi gedung bertingkat tinggi', 'https://images.unsplash.com/photo-1486718448742-163732cd1544?w=800', 'published', (SELECT id FROM profiles LIMIT 1), NOW() - INTERVAL '8 days'),

('Renovasi dan Retrofit Bangunan Bersejarah', 'renovasi-retrofit-bangunan-bersejarah', '<p>Renovasi bangunan bersejarah memerlukan pendekatan khusus yang menghormati nilai historis sambil meningkatkan fungsionalitas modern.</p><p>Kami ahli dalam mempertahankan karakter arsitektural sambil mengintegrasikan sistem modern untuk kenyamanan dan keamanan.</p><p>Setiap proyek renovasi adalah keseimbangan antara preservasi dan inovasi.</p>', 'Bagaimana kami mempertahankan warisan sambil memodernisasi bangunan', 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800', 'published', (SELECT id FROM profiles LIMIT 1), NOW() - INTERVAL '9 days'),

('Smart Building: Masa Depan Konstruksi', 'smart-building-masa-depan-konstruksi', '<p>Smart building mengintegrasikan teknologi IoT untuk menciptakan lingkungan yang efisien, nyaman, dan berkelanjutan. Sistem otomasi gedung mengoptimalkan penggunaan energi dan meningkatkan pengalaman penghuni.</p><p>Kami membangun gedung pintar yang dapat beradaptasi dengan kebutuhan penghuni dan kondisi lingkungan.</p><p>Investasi dalam smart building adalah investasi untuk efisiensi jangka panjang.</p>', 'Teknologi smart building dan implementasinya dalam proyek modern', 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800', 'published', (SELECT id FROM profiles LIMIT 1), NOW() - INTERVAL '10 days'),

('Konstruksi Prefabrikasi: Efisiensi dan Kecepatan', 'konstruksi-prefabrikasi-efisiensi-kecepatan', '<p>Konstruksi prefabrikasi menawarkan solusi cepat tanpa mengorbankan kualitas. Komponen yang diproduksi di pabrik mengurangi waktu konstruksi di lokasi.</p><p>Metode ini juga mengurangi limbah dan meningkatkan kontrol kualitas. Kami menggunakan prefabrikasi untuk proyek-proyek yang memerlukan penyelesaian cepat.</p><p>Efisiensi waktu berarti penghematan biaya untuk klien kami.</p>', 'Keuntungan dan aplikasi konstruksi prefabrikasi dalam proyek modern', 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800', 'published', (SELECT id FROM profiles LIMIT 1), NOW() - INTERVAL '11 days'),

('Manajemen Risiko dalam Proyek Konstruksi Besar', 'manajemen-risiko-proyek-konstruksi-besar', '<p>Proyek konstruksi besar melibatkan berbagai risiko yang harus dikelola dengan hati-hati. Dari risiko keuangan hingga risiko operasional, kami memiliki strategi komprehensif.</p><p>Identifikasi dini dan mitigasi risiko adalah kunci kesuksesan proyek. Tim kami berpengalaman dalam mengelola proyek kompleks dengan berbagai tantangan.</p><p>Perencanaan yang matang dan eksekusi yang tepat meminimalkan risiko.</p>', 'Strategi kami dalam mengidentifikasi dan mengelola risiko proyek', 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800', 'published', (SELECT id FROM profiles LIMIT 1), NOW() - INTERVAL '12 days'),

('Sertifikasi Green Building: Standar dan Implementasi', 'sertifikasi-green-building-standar-implementasi', '<p>Sertifikasi green building seperti LEED dan EDGE menjadi standar baru dalam konstruksi berkelanjutan. Kami membantu klien mencapai sertifikasi ini melalui desain dan konstruksi yang tepat.</p><p>Dari efisiensi energi hingga penggunaan material berkelanjutan, setiap aspek dioptimalkan untuk memenuhi standar sertifikasi.</p><p>Gedung bersertifikat meningkatkan nilai properti dan mengurangi biaya operasional.</p>', 'Panduan mencapai sertifikasi green building untuk proyek Anda', 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800', 'published', (SELECT id FROM profiles LIMIT 1), NOW() - INTERVAL '13 days'),

('Kolaborasi Tim: Kunci Kesuksesan Proyek', 'kolaborasi-tim-kunci-kesuksesan-proyek', '<p>Proyek konstruksi yang sukses memerlukan kolaborasi yang kuat antara berbagai pihak: arsitek, insinyur, kontraktor, dan klien. Komunikasi yang efektif adalah fondasi kolaborasi yang baik.</p><p>Kami menggunakan platform kolaborasi digital untuk memastikan semua pihak selalu terinformasi dan terlibat dalam proses.</p><p>Teamwork yang solid menghasilkan proyek yang lebih baik dan lebih cepat.</p>', 'Pentingnya kolaborasi dan komunikasi dalam eksekusi proyek', 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800', 'published', (SELECT id FROM profiles LIMIT 1), NOW() - INTERVAL '14 days'),

('Tren Desain Arsitektur Modern di Indonesia', 'tren-desain-arsitektur-modern-indonesia', '<p>Arsitektur modern di Indonesia menggabungkan estetika kontemporer dengan elemen tradisional lokal. Tren saat ini mencakup desain minimalis, penggunaan material alami, dan integrasi dengan alam.</p><p>Kami bekerja dengan arsitek terbaik untuk menciptakan bangunan yang tidak hanya fungsional tetapi juga inspiratif.</p><p>Desain yang baik meningkatkan kualitas hidup dan mencerminkan identitas pemiliknya.</p>', 'Eksplorasi tren arsitektur terkini dan penerapannya di Indonesia', 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800', 'published', (SELECT id FROM profiles LIMIT 1), NOW() - INTERVAL '15 days');
