// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzzyqentnmitkgnffgsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16enlxZW50bm1pdGtnbmZmZ3NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxNjQ2OTQsImV4cCI6MjA3Nzc0MDY5NH0.GAQEBaUHD2P7J4Bp0hIg5HogQzP14kZfenZGs1EOSjk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});